import type { Skill } from "../types";

export const SKILL_CATALOG: Skill[] = [
  {
    id: "contract-review-pro",
    name: "合同审阅 Pro",
    author: "King & Wood Labs",
    source: "official",
    kind: "skill",
    icon: "⚖",
    category: "合同审阅",
    description:
      "对任意中英文合同执行结构化审阅,自动标注风险条款、缺失条款,与所内审阅标准对齐。",
    rating: 4.9,
    installs: 12402,
    version: "2.1.0",
    featured: true,
    userGroups: ["law-firm", "in-house"],
    exposes: [
      {
        name: "skill.contract_review",
        description:
          "Review a contract clause-by-clause. Returns list of issues with severity (high/mid/low), citations, and proposed rewrites.",
        inputSchema: {
          type: "object",
          properties: {
            text: { type: "string", description: "Contract text to review" },
            jurisdiction: { type: "string", description: "e.g. PRC, HK, SG" },
          },
          required: ["text"],
        },
      },
    ],
  },
  {
    id: "data-sanitization",
    name: "数据脱敏 · Data Sanitization",
    author: "官方",
    source: "official",
    kind: "skill",
    icon: "🔒",
    category: "数据脱敏",
    description: "在交付外部前自动脱敏当事人、金额、身份证件、商业秘密,可配置粒度与白名单。",
    rating: 4.8,
    installs: 8217,
    version: "1.6.2",
    featured: true,
    userGroups: ["law-firm", "in-house", "judiciary", "other"],
    exposes: [
      {
        name: "skill.sanitize",
        description:
          "Sanitize text by replacing PII / parties / amounts with placeholders. Returns mapping + sanitized text.",
        inputSchema: {
          type: "object",
          properties: {
            text: { type: "string" },
            level: { type: "string", enum: ["low", "medium", "high"] },
          },
          required: ["text"],
        },
      },
    ],
  },
  {
    id: "browser-automation",
    name: "浏览器自动化",
    author: "合作伙伴",
    source: "partner",
    kind: "skill",
    icon: "🌐",
    category: "浏览器自动化",
    description: "让 Agent 操作浏览器——登录企查查、下载工商档案、批量截图存档,无人值守。",
    rating: 4.7,
    installs: 5901,
    version: "0.9.4",
    featured: true,
    userGroups: ["law-firm", "in-house"],
    exposes: [
      {
        name: "skill.browser_fetch",
        description: "Fetch a URL via headless browser, returns text + screenshot.",
        inputSchema: {
          type: "object",
          properties: { url: { type: "string" } },
          required: ["url"],
        },
      },
    ],
  },
  {
    id: "mcp-admin-penalty",
    name: "行政处罚数据库",
    author: "官方",
    source: "official",
    kind: "mcp",
    icon: "📚",
    category: "检索 · MCP",
    description:
      "通过 Model Context Protocol 接入全国市场监管行政处罚公示库,实时可查、可引用、可关联。",
    rating: 4.9,
    installs: 9883,
    version: "3.0.1",
    featured: true,
    userGroups: ["law-firm", "in-house", "judiciary"],
    exposes: [
      {
        name: "mcp.admin_penalty.search",
        description:
          "Search administrative penalty records by company name, related entities, year range.",
        inputSchema: {
          type: "object",
          properties: {
            company: { type: "string", description: "Company name or fuzzy match" },
            includeRelated: { type: "boolean" },
            yearFrom: { type: "integer" },
            yearTo: { type: "integer" },
          },
          required: ["company"],
        },
      },
    ],
  },
  {
    id: "mcp-pkulaw",
    name: "北大法宝",
    author: "北大法宝",
    source: "partner",
    kind: "mcp",
    icon: "⚖",
    category: "检索 · MCP",
    description: "接入北大法宝法律法规与判例库,按法条精准引用、按要旨推送类案。",
    rating: 4.8,
    installs: 14302,
    version: "5.2.0",
    userGroups: ["law-firm", "in-house", "judiciary", "other"],
    exposes: [
      {
        name: "mcp.pkulaw.lookup_statute",
        description: "Look up a specific PRC statute article by name + article number.",
        inputSchema: {
          type: "object",
          properties: {
            statute: { type: "string", description: "e.g. 公司法 / 民法典" },
            article: { type: "string", description: "e.g. 第一百一十五条" },
          },
          required: ["statute", "article"],
        },
      },
    ],
  },
  {
    id: "mcp-samr",
    name: "SAMR 信用公示",
    author: "国家市场监督管理总局",
    source: "official",
    kind: "mcp",
    icon: "🏛",
    category: "检索 · MCP",
    description: "查询企业基本信息、股东、对外投资、行政许可、年报、联合奖惩等。",
    rating: 4.8,
    installs: 7611,
    version: "2.4.1",
    userGroups: ["law-firm", "in-house"],
    exposes: [
      {
        name: "mcp.samr.lookup_entity",
        description: "Look up entity registration info by name or unified social credit code.",
        inputSchema: {
          type: "object",
          properties: { query: { type: "string" } },
          required: ["query"],
        },
      },
    ],
  },
  {
    id: "mcp-wkinfo",
    name: "威科先行",
    author: "威科",
    source: "partner",
    kind: "mcp",
    icon: "📖",
    category: "检索 · MCP",
    description: "类案检索、要点推送、英文判例对照。",
    rating: 4.7,
    installs: 6840,
    version: "1.8.0",
    userGroups: ["law-firm", "judiciary", "other"],
    exposes: [
      {
        name: "mcp.wkinfo.search_cases",
        description:
          "Search similar cases by keywords + court level + date range. Returns top 10 with summaries.",
        inputSchema: {
          type: "object",
          properties: {
            keywords: { type: "string" },
            court: { type: "string" },
          },
          required: ["keywords"],
        },
      },
    ],
  },
  {
    id: "prospectus-check",
    name: "招股说明书模板检查",
    author: "King & Wood Labs",
    source: "labs",
    kind: "skill",
    icon: "📝",
    category: "文书起草",
    description: "按交易所规则校验招股书必要章节、口径与披露完备性。",
    rating: 4.8,
    installs: 3214,
    version: "1.4.0",
    userGroups: ["law-firm"],
  },
  {
    id: "related-party-tx",
    name: "关联交易自动梳理",
    author: "官方",
    source: "official",
    kind: "skill",
    icon: "🔗",
    category: "实务工作流",
    description: "读取工商关联图谱与合同库,生成关联交易披露表与潜在冲突清单。",
    rating: 4.7,
    installs: 2811,
    version: "1.2.1",
    userGroups: ["law-firm", "in-house"],
  },
  {
    id: "spa-drafter",
    name: "SPA 条款生成器",
    author: "官方",
    source: "official",
    kind: "skill",
    icon: "📑",
    category: "文书起草",
    description: "根据交易要素清单,生成带备选条款的 SPA 草稿,支持中英对照。",
    rating: 4.9,
    installs: 4112,
    version: "2.0.3",
    userGroups: ["law-firm"],
  },
  {
    id: "legal-translate",
    name: "法律双语翻译",
    author: "官方",
    source: "official",
    kind: "skill",
    icon: "🌍",
    category: "翻译 · 多语",
    description: "保留条款编号与术语一致性的法律文本翻译,中英、中德、中日。",
    rating: 4.7,
    installs: 6803,
    version: "3.1.0",
    userGroups: ["law-firm", "in-house", "judiciary", "other"],
  },
  {
    id: "financial-skim",
    name: "财务尽调速读",
    author: "合作伙伴",
    source: "partner",
    kind: "skill",
    icon: "📊",
    category: "实务工作流",
    description: "从财报中提取关键比率与异常项,联动法律风险点。",
    rating: 4.6,
    installs: 2110,
    version: "0.9.2",
    userGroups: ["law-firm", "in-house"],
  },
  {
    id: "evidence-index",
    name: "证据目录生成",
    author: "社区",
    source: "community",
    kind: "skill",
    icon: "🗂",
    category: "实务工作流",
    description: "扫描案件证据文件夹,生成符合法院要求的证据清单与编号。",
    rating: 4.5,
    installs: 1402,
    version: "0.6.0",
    userGroups: ["law-firm", "judiciary"],
  },
  {
    id: "charter-diff",
    name: "章程条款比对",
    author: "King & Wood Labs",
    source: "labs",
    kind: "skill",
    icon: "🧩",
    category: "实务工作流",
    description: "将公司章程与所内标准条款库比对,标注偏离与潜在风险。",
    rating: 4.8,
    installs: 1903,
    version: "1.1.0",
    userGroups: ["law-firm", "in-house"],
  },

  /* ============================================
   * 司法工作者专属
   * ============================================ */
  {
    id: "mcp-court-docs",
    name: "中国裁判文书网",
    author: "最高人民法院 / 公开数据",
    source: "official",
    kind: "mcp",
    icon: "⚖",
    category: "检索 · MCP",
    description: "按案号、当事人、法律关系、审判组织检索全国裁判文书;支持引文格式输出。",
    rating: 4.9,
    installs: 6201,
    version: "2.1.0",
    userGroups: ["judiciary", "law-firm"],
    exposes: [
      {
        name: "mcp.court_docs.search",
        description:
          "Search court judgment documents by keyword / case type / court level / year.",
        inputSchema: {
          type: "object",
          properties: {
            keywords: { type: "string" },
            court: { type: "string" },
            year: { type: "integer" },
          },
          required: ["keywords"],
        },
      },
    ],
  },
  {
    id: "judgment-drafter",
    name: "裁判文书起草助手",
    author: "司法 AI 实验室",
    source: "labs",
    kind: "skill",
    icon: "📜",
    category: "文书起草",
    description:
      '按照法院文书规范生成判决书 / 裁定书初稿,自动套入「本院查明 / 本院认为 / 判决主文」结构。',
    rating: 4.7,
    installs: 1840,
    version: "1.3.0",
    userGroups: ["judiciary"],
  },
  {
    id: "evidence-chain",
    name: "证据链可视化",
    author: "司法 AI 实验室",
    source: "labs",
    kind: "skill",
    icon: "🔗",
    category: "实务工作流",
    description: "解析卷宗证据,自动构建时间线与逻辑链路图,识别证据缺口。",
    rating: 4.6,
    installs: 1120,
    version: "0.8.4",
    userGroups: ["judiciary", "law-firm"],
  },

  /* ============================================
   * 公司法务专属
   * ============================================ */
  {
    id: "internal-clause-lib",
    name: "内部条款标准库",
    author: "官方",
    source: "official",
    kind: "skill",
    icon: "📚",
    category: "合同审阅",
    description: "对接公司内部条款标准库,实时比对待审合同与公司标准条款的偏离,出具修订建议。",
    rating: 4.7,
    installs: 2240,
    version: "1.5.0",
    userGroups: ["in-house"],
  },
  {
    id: "esg-compliance",
    name: "ESG / 反舞弊合规",
    author: "合规研究院",
    source: "partner",
    kind: "skill",
    icon: "🌱",
    category: "合规检查",
    description:
      "按 ISO 37301 / 反舞弊指引 / ESG 披露要求,自动生成合规年审清单与高风险事项排查报告。",
    rating: 4.6,
    installs: 1503,
    version: "1.1.0",
    userGroups: ["in-house"],
  },
  {
    id: "internal-investigation",
    name: "内部调查工作包",
    author: "官方",
    source: "official",
    kind: "skill",
    icon: "🔍",
    category: "实务工作流",
    description: "包含访谈记录模板、证据保全清单、调查报告框架;支持脱敏导出。",
    rating: 4.5,
    installs: 980,
    version: "0.9.0",
    userGroups: ["in-house"],
  },

  /* ============================================
   * 其它专业(仲裁员、学者等)
   * ============================================ */
  {
    id: "mcp-arbitration-rules",
    name: "仲裁规则与机构库",
    author: "国际仲裁实践研究",
    source: "partner",
    kind: "mcp",
    icon: "🏛",
    category: "检索 · MCP",
    description:
      "ICC / SIAC / HKIAC / CIETAC / LCIA / ICSID 等主要仲裁规则、机构费率、典型案例。",
    rating: 4.8,
    installs: 1822,
    version: "1.4.0",
    userGroups: ["other", "law-firm"],
    exposes: [
      {
        name: "mcp.arbitration.lookup_rule",
        description: "Look up a specific arbitration rule article from the named institution.",
        inputSchema: {
          type: "object",
          properties: {
            institution: { type: "string", description: "ICC / SIAC / HKIAC / CIETAC ..." },
            article: { type: "string" },
          },
          required: ["institution", "article"],
        },
      },
    ],
  },
  {
    id: "comparative-law",
    name: "比较法检索助手",
    author: "学术合作",
    source: "community",
    kind: "skill",
    icon: "🌐",
    category: "检索",
    description: "跨法域检索同一法律问题在不同司法管辖区的处理路径,适用于学术与跨境业务。",
    rating: 4.4,
    installs: 760,
    version: "0.7.0",
    userGroups: ["other", "law-firm"],
  },
  {
    id: "notary-template",
    name: "公证文书模板包",
    author: "司法部公证业务指导",
    source: "official",
    kind: "skill",
    icon: "📑",
    category: "文书起草",
    description: "按公证业务类型(继承、委托、合同、声明)套用标准公证文书模板。",
    rating: 4.6,
    installs: 540,
    version: "1.0.2",
    userGroups: ["other"],
  },
];

export function skillById(id: string): Skill | undefined {
  return SKILL_CATALOG.find((s) => s.id === id);
}
